version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: echo "A first hello"
  deployment:
    commands:
        - docker login -e ngocduy9891@gmail.com -u ngocduy9891 -p Duy13121989@
        - docker push ngocduy9891/python
        - ./start.sh
