version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - run: echo "A first hello1"
deployment:
    commands:
        - docker login -e ngocduy9891@gmail.com -u ngocduy9891 -p Duy13121989@
        - docker build -t ngocduy9891/python .
        - docker push ngocduy9891/python
        - ./start.sh
